version: 0.0
os: linux
files:
  - source: /target/*.jar  # Assuming the JAR file is located under 'target'
    destination: /home/ec2-user/my-springboot-app/  # Customize based on where you want to deploy

hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_springboot.sh
      timeout: 300
      runas: root
