
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing Maven...
      - curl -sL https://apache.mirror.digitalpacific.com.au/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz | tar xz -C /usr/local
      - export PATH=$PATH:/usr/local/apache-maven-3.6.3/bin
      - mvn --version

  build:
    commands:
      - echo Building the app with Maven...
      - mvn clean install

artifacts:
  files:
    - '**/*'
    - target/*.jar
