name: Docker Build & Push

on:
  push:
    branches: [ "main" ]  # Runs on pushes to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          docker build -t raghav3168/spring-petclinic:latest .
          docker push raghav3168/spring-petclinic:latest
